// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABBNQr0KXkf0ZxFEo61H6gcYlQw-KdFMw',
    appId: '1:541096490711:android:255f37843926fd9b826292',
    messagingSenderId: '541096490711',
    projectId: 'mamabhanjaus1',
    databaseURL: 'https://mamabhanjaus1-default-rtdb.firebaseio.com',
    storageBucket: 'mamabhanjaus1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZqA_Mc-_DVXpHm0qNjHfLAeVx-TeWCU',
    appId: '1:541096490711:ios:b353dcc67e99db40826292',
    messagingSenderId: '541096490711',
    projectId: 'mamabhanjaus1',
    databaseURL: 'https://mamabhanjaus1-default-rtdb.firebaseio.com',
    storageBucket: 'mamabhanjaus1.firebasestorage.app',
    androidClientId: '541096490711-2d903tm33bl8ul6ho3kv3kpg0o8fcle3.apps.googleusercontent.com',
    iosClientId: '541096490711-dcf851ur07q1v5is5jv4edn76f7ptrqc.apps.googleusercontent.com',
    iosBundleId: 'com.mamabhanja.driver',
  );

}